name: Update Parent Repository abes-documentation-api-publish

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher le workflow du dépôt abes-documentation-api-publish
        run: |
          branches=("main" "test" "develop")
          for branch in "${branches[@]}"; do
            curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB_FOR_GITHUB_ACTION }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/abes-esr/abes-documentation-api-publish/dispatches \
            --data '{"event_type": "update_config_files", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          done